import { MobileActionBar, SiteFooter, SiteHeader } from "@/app/site-chrome";
import type { Metadata } from "next";
import { business, displayPhone, telHref, whatsappHref } from "@/lib/business";
import { districts } from "@/lib/districts";
export const metadata: Metadata = {
  title: "İletişim ve 7/24 Mobil Lastik Servisi",
  description: "Kahraman Oto Lastik'e 0543 894 55 60 numarasından 7/24 ulaşın. İstanbul'un 39 ilçesinde mobil lastik hizmeti; sabit mağaza adresi bulunmuyor.",
  alternates: { canonical: "/iletisim" },
  openGraph: { type: "website", locale: "tr_TR", url: `${business.url}/iletisim`, title: "Kahraman Oto Lastik İletişim | 7/24", description: "İstanbul'da 7/24 mobil lastik desteği için arayın veya WhatsApp'tan konum gönderin." },
};
export default function ContactPage() {
 const schema = { "@context": "https://schema.org", "@type": "ContactPage", name: "Kahraman Oto Lastik iletişim", url: `${business.url}/iletisim`, mainEntity: { "@type": "AutomotiveBusiness", name: business.name, telephone: business.phone, url: business.url, openingHours: "Mo-Su 00:00-23:59", areaServed: districts.map(({ name }) => ({ "@type": "AdministrativeArea", name: `${name}, İstanbul` })), description: "Sabit müşteri adresi bulunmayan, İstanbul'un 39 ilçesinde mobil lastik hizmeti veren işletme." } };
 return <><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><main className="area-page contact-page"><nav className="breadcrumbs" aria-label="Sayfa yolu"><a href="/">Ana sayfa</a><span>/</span><span>İletişim</span></nav><section className="area-hero"><div className="eyebrow"><span>7 GÜN • 24 SAAT</span><i/></div><h1>Yardım için<br/><em>bize ulaşın.</em></h1><p>Kahraman Oto Lastik sabit mağaza adresi olmayan mobil servistir. İstanbul'un 39 ilçesinde, bulunduğunuz noktaya uygunluk için arayın veya WhatsApp üzerinden konum gönderin.</p><div className="hero-actions"><a className="button button-dark" href={telHref()}><span className="button-icon">↗</span> {displayPhone} • Hemen ara</a><a className="button button-line" href={whatsappHref()}>WhatsApp’tan yaz <span>↗</span></a></div></section><section className="contact-detail-grid"><article><span className="contact-detail-icon">☎</span><small>TELEFON</small><h2>{displayPhone}</h2><a href={telHref()}>Telefonla ara ↗</a></article><article><span className="contact-detail-icon">◷</span><small>ÇALIŞMA SAATİ</small><h2>Her gün, 7/24</h2><p>Servis uygunluğunu arayarak teyit edin.</p></article><article><span className="contact-detail-icon">⌖</span><small>HİZMET ŞEKLİ</small><h2>Mobil servis</h2><p>Sabit müşteri kabul adresi bulunmuyor.</p></article></section><section className="contact-instructions"><div><div className="eyebrow"><span>ARARKEN PAYLAŞIN</span><i/></div><h2>Konum, araç,<br/><em>lastik ihtiyacı.</em></h2></div><ol><li><b>Konumunuzu:</b> ilçe, mahalle ve mümkünse WhatsApp konum piniyle iletin.</li><li><b>Araç türünü:</b> binek, SUV ya da ağır vasıta olarak belirtin.</li><li><b>İhtiyacınızı:</b> değişim veya tamir, lastik ebatı ve varsa hasar bilgisiyle anlatın.</li></ol></section><section className="contact-area-links"><div className="eyebrow"><span>İSTANBUL'UN 39 İLÇESİ</span><i/></div><h2>Hizmet bölgenizi<br/><em>seçin.</em></h2><ul>{districts.map(({ slug, name }) => <li key={slug}><a href={`/hizmet-bolgeleri/${slug}`}>{name} mobil lastikçi <span>↗</span></a></li>)}</ul><a className="text-link" href="/hizmet-bolgeleri">Tüm hizmet bölgelerini gör ↗</a></section></main><SiteFooter/><MobileActionBar/></>;
}
